"""add_employee_barcode

Revision ID: a6701d50481d
Revises: 19816ebd6413
Create Date: 2026-07-17 01:35:07.296787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6701d50481d'
down_revision: Union[str, None] = '19816ebd6413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('barcode', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_barcode'), 'users', ['barcode'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_barcode'), table_name='users')
    op.drop_column('users', 'barcode')
    # ### end Alembic commands ###
