from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime, date

# ==================== GENERIC SCHEMAS ====================

class PaginationParams(BaseModel):
    page: int = 1
    page_size: int = 20
    search: Optional[str] = None
    sort_by: Optional[str] = "created_at"
    sort_order: Optional[str] = "desc"

class PaginatedResponse(BaseModel):
    items: list
    total: int
    page: int
    page_size: int
    total_pages: int

class MessageResponse(BaseModel):
    message: str
    success: bool = True


# ==================== AUTH / USER SCHEMAS ====================

class Token(BaseModel):
    access_token: str
    refresh_token: str
    token_type: str = "bearer"

class TokenData(BaseModel):
    user_id: int
    email: str
    role: str

class LoginRequest(BaseModel):
    email: str
    password: str

class UserBase(BaseModel):
    email: str
    username: str
    full_name: str
    phone: Optional[str] = None
    role: str = "operator"

class UserCreate(UserBase):
    password: str

class UserUpdate(BaseModel):
    full_name: Optional[str] = None
    phone: Optional[str] = None
    role: Optional[str] = None
    is_active: Optional[bool] = None

class UserResponse(UserBase):
    id: int
    is_active: bool
    created_at: datetime

    class Config:
        from_attributes = True


# ==================== MANUFACTURING MASTERS ====================

class CategoryBase(BaseModel):
    name: str
    description: Optional[str] = None

class CategoryCreate(CategoryBase):
    pass

class CategoryResponse(CategoryBase):
    id: int
    created_at: datetime
    class Config:
        from_attributes = True

class FabricBase(BaseModel):
    name: str
    fabric_type: Optional[str] = None
    gsm: Optional[str] = None
    composition: Optional[str] = None
    color: Optional[str] = None

class FabricCreate(FabricBase):
    pass

class FabricResponse(FabricBase):
    id: int
    created_at: datetime
    class Config:
        from_attributes = True

class ProductBase(BaseModel):
    code: str
    name: str
    category_id: Optional[int] = None
    fabric_id: Optional[int] = None
    available_sizes: Optional[List[str]] = None
    image_url: Optional[str] = None

class ProductCreate(ProductBase):
    pass

class ProductResponse(ProductBase):
    id: int
    created_at: datetime
    class Config:
        from_attributes = True

class DesignBase(BaseModel):
    design_number: str
    name: str
    product_id: Optional[int] = None
    category_id: Optional[int] = None
    fabric_id: Optional[int] = None
    image_url: Optional[str] = None
    version: Optional[str] = None

class DesignCreate(DesignBase):
    pass

class DesignResponse(DesignBase):
    id: int
    created_at: datetime
    class Config:
        from_attributes = True


# ==================== LOT & PRODUCTION SCHEMAS ====================

class LotBase(BaseModel):
    design_id: int
    product_id: int
    size: str
    quantity: int

class LotCreate(LotBase):
    # lot_number and barcode are auto-generated by the backend
    pass

class LotResponse(LotBase):
    id: int
    lot_number: str
    barcode: Optional[str] = None
    current_process: Optional[str] = None
    created_at: datetime
    class Config:
        from_attributes = True

class ScanRequest(BaseModel):
    barcode: str
    employee_id: Optional[int] = None

class ScanResponse(BaseModel):
    success: bool
    message: str
    lot_number: Optional[str] = None
    previous_stage: Optional[str] = None
    new_stage: Optional[str] = None

class BarcodeScanHistoryResponse(BaseModel):
    id: int
    barcode: str
    scan_type: str
    scanned_by: Optional[int] = None
    process_stage: Optional[str] = None
    remarks: Optional[str] = None
    created_at: datetime
    class Config:
        from_attributes = True


# ==================== ATTENDANCE SCHEMAS ====================

class AttendanceBase(BaseModel):
    employee_id: int
    date: date
    status: str
    scan_type: Optional[str] = None
    shift: Optional[str] = None

class AttendanceCreate(AttendanceBase):
    pass

class AttendanceResponse(AttendanceBase):
    id: int
    created_at: datetime
    class Config:
        from_attributes = True

# ==================== DASHBOARD SCHEMAS ====================
class DashboardStats(BaseModel):
    today_production: int
    pending_lots: int
    completed_lots: int
    active_employees: int
